Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2349, in _normalize_cached
    return _cache[filename]
KeyError: '/usr/lib/python3.8'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/accelergy", line 5, in <module>
    from accelergy.accelergy_console import main
  File "/usr/local/lib/python3.8/dist-packages/accelergy/accelergy_console.py", line 34, in <module>
    from accelergy.io import parse_commandline_args, generate_output_files
  File "/usr/local/lib/python3.8/dist-packages/accelergy/io.py", line 25, in <module>
    import pyfiglet
  File "/usr/local/lib/python3.8/dist-packages/pyfiglet/__init__.py", line 11, in <module>
    import pkg_resources
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 575, in _build_master
    ws = cls()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 568, in __init__
    self.add_entry(entry)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 624, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2040, in find_on_path
    path_item = _normalize_cached(path_item)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2351, in _normalize_cached
    _cache[filename] = result = normalize_path(filename)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2332, in normalize_path
    return os.path.normcase(os.path.realpath(os.path.normpath(
  File "/usr/lib/python3.8/posixpath.py", line 391, in realpath
    path, ok = _joinrealpath(filename[:0], filename, {})
  File "/usr/lib/python3.8/posixpath.py", line 425, in _joinrealpath
    if not islink(newpath):
  File "/usr/lib/python3.8/posixpath.py", line 167, in islink
    st = os.lstat(path)
KeyboardInterrupt
